### ISSUE TITLE
Add "hacktoberfest" topic to repository

### ISSUE THREAD

**Issue by hrishikeshcs** [codezoned/ScriptsDump#243]
For a the repository to be eligible, the "hacktoberfest" topic has to be added to the repository. If not added, the accepted PRs will not be counted, as per the [Hacktoberfest update on 3rd October](https://hacktoberfest.digitalocean.com/hacktoberfest-update). If the topic can't be added, a "hacktoberfest-accepted" label can be added to a PR that is being accepted.

**Comment by master-fury** [comment]
Now it's done! Thanks, @hrishikeshcs
